# Use the official Nginx base image.
FROM nginx:latest

# Copy static website files (HTML, CSS, JS) into the default Nginx web directory
COPY index.html /usr/share/nginx/html

# Expose port 80 for HTTP traffic.
EXPOSE 80 
##
##
##
