name: APP Deployment and Cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-branch
    paths:
      - app/**
  pull_request:
    branches:
      - main
    paths:
        - app/**
 
jobs:

 # Job-1     
 Build-publish-app:
   name: App builder and publisher
   runs-on: ubuntu-latest
   env:
     AWS_REGION: us-east-1
     ECR_REPOSITORY: r3z5w8y3/dprofileapp  # Change to your AWS Public ECR alias
      
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Docker login
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws_region: ${{env.AWS_REGION}}
  
  
    - name: Build image
      run: |
        docker build . --tag ${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest 
        docker push ${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        working-directory: app

# - name: Docker login build and push Docker Image to Public ECR
      #   uses: appleboy/docker-ecr-action@master
      #   with:
      #     access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     registry: ${{ env.REGISTRY }}
      #     repository: ${{ env.ECR_REPOSITORY }}
      #     region: ${{ env.AWS_REGION }}
      #     auto_tag: true
      #     daemon_off: false
      #     dockerfile: app/Dockerfile
      #     context: app